export const environment = {
  production: false,
  baseEndpoint: 'http://localhost:8081/',
  countriesEndpoint: 'https://restcountries.com/v3.1/',
  citiesTeleportEndpoint: 'https://api.teleport.org/api/',
  citiesQWeatherEndpoint: 'https://geoapi.qweather.com/v2/',
  overpassapiEndpoint: 'https://overpass-api.de/api/interpreter',
  nominatimEndpoint: 'https://nominatim.openstreetmap.org/',
  wikipediaEndpoint: 'https://{{lng}}.wikipedia.org/w/api.php',
  wikidataEndpoint: 'https://www.wikidata.org/w/rest.php/wikibase/v0/',
  wikimediaEndpiint: 'https://commons.wikimedia.org/w/',
  photonEndpoint: 'https://photon.komoot.io/api/',
  pastvuEndpoint: 'https://pastvu.com/',
  pixabayEndpoint: 'https://pixabay.com/api/',
  pixabayKey: '39437353-c3c8f978595af484ac5f324c8',
};
