name: CI/CD Pipeline
on:
  push:
    branches: [ dev_workflow ]
env:
  # Setting an environment variable with the value of a configuration variable
  REP_VAR: ${{ vars.REP_VAR }}
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: List Variables
              run: |
                  echo "aws public IP : $AWS_PUBLIC_IP"
                  echo "$GITHUB_WORKSPACE"
              env:
                  AWS_PUBLIC_IP: ${{ vars.AWS_PUBLIC_IP }}
            - name: List artifacts
              run: |
                ls -laF $GITHUB_WORKSPACE
                pwd
