name: CI/CD Pipeline
on:
  push:
    branches: [ dev_workflow ]
env:
  # Setting an environment variable with the value of a configuration variable
  REP_VAR: ${{ vars.REP_VAR }}
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        environment: dev_workflow
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
                node-version: 18
          - name: "check is AWS_PUBLIC_IP exists"
            env: 
                super_secret: ${{ secrets.AWS_PUBLIC_IP }}
            if: ${{ env.super_secret == '' }}
            run: echo "doesnt exist"
          - name: Copy folder content recursively to AWS
            uses: garygrossgarten/github-action-scp@release
            with:
              local: $GITHUB_WORKSPACE/stc/index.html
              remote: /home/ec2-user/test
              host: ${{ secrets.AWS_PUBLIC_IP }}
              username: ${{ secrets.AWS_SSH_USER }}
              privateKey : ${{ secrets.AWS_SSH_PRIVATE_KEY }}
                
