name: CI/CD Pipeline
on:
  push:
    branches: [ dev_workflow ]
env:
  # Setting an environment variable with the value of a configuration variable
  REP_VAR: ${{ vars.REP_VAR }}
jobs:
    deployment:
        runs-on: ubuntu-latest
        environment: dev_workflow
        steps:
            - uses: actions/checkout@v3
            - name: List Variables
              run: |
                  echo "aws public IP : $PUBLIC_IP"
                  echo "aws public IP2: {{ vars.AWS_PUBLIC_IP }}"
                  echo "workspace: $GITHUB_WORKSPACE"
              env:
                  PUBLIC_IP: ${{ vars.AWS_PUBLIC_IP }}
            - name: List artifacts
              run: |
                ls -laF /home/runner/work/travale
                ls -laF $GITHUB_WORKSPACE
                pwd
                
                
