name: CI/CD Pipeline
on:
  push:
    branches: [ dev_workflow ]
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
                node-version: 18
          - run: npm ci
    deployment:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
         # Step 1
          - name: List artifacts
            run: ls -laF ../../dest 
