name: CI/CD Pipeline
on:
  push:
    branches: [ dev_workflow ]
env:
  # Setting an environment variable with the value of a configuration variable
  REP_VAR: ${{ vars.REP_VAR }}
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        environment: dev_workflow
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
                node-version: 18
          - name: ping
            run: ping ${{ secrets.AWS_PUBLIC_IP }}
          - name: copy file via ssh key
            uses: appleboy/scp-action@master
            with:
              host: ${{ secrets.AWS_PUBLIC_IP }}
              username: ${{ secrets.AWS_SSH_USER }}
              port: 22
              key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
              source: "$GITHUB_WORKSPACE/src/index.html"
              target: "/home/ec2-user/test"
                
                
