name: CI/CD Pipeline
on:
  push:
    branches: [ dev_workflow ]
env:
  # Setting an environment variable with the value of a configuration variable
  REP_VAR: ${{ vars.REP_VAR }}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
                node-version: 18
          - run: npm ci
          - run: npm run -s build
    deployment:
        runs-on: ubuntu-latest
        needs: [build]
        environment: dev_workflow
        steps:
            - uses: actions/checkout@v3
            - name: List Variables
              run: |
                  echo "aws public IP : $PUBLIC_IP"
                  echo "workspace: $GITHUB_WORKSPACE"
              env:
                  PUBLIC_IP: ${{ vars.AWS_PUBLIC_IP }}
            - name: List artifacts
                ls -laF $GITHUB_WORKSPACE
                ls -laF $GITHUB_WORKSPACE/dist
                
                
