name: CI/CD Pipeline
on:
  push:
    branches: [ dev_workflow ]
env:
  # Setting an environment variable with the value of a configuration variable
  REP_VAR: ${{ vars.REP_VAR }}
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        environment: dev_workflow
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
                node-version: 18
          - name: NPM install
            run: npm ci          
          - name: Copy folder content recursively to AWS
            uses: garygrossgarten/github-action-scp@release
            with:
              local: ${{ vars.GITHUB_WORKSPACE }}src/assets/test_images/
              remote: /home/ec2-user/test
              host: ${{ secrets.AWS_PUBLIC_IP }}
              username: ${{ secrets.AWS_SSH_USER }}
              password: ${{ secrets.AWS_SSH_PWD }}
